# Generated by Django 5.2.3 on 2025-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusername',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramusername',
            name='telegram_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
